apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: adrift
  name: adrift
  namespace: adrift  # Sets Namespace
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: adrift
  template:
    metadata:
      labels:
        app.kubernetes.io/name: adrift
    spec:
      containers:
        - name: adrift
          image: ghcr.io/pyflowops/adrift:local
          imagePullPolicy: Never  # The image is pre-loaded using 'kind load docker-image'
          # Enironment Vars from Secrets examples
          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: adrift
                  key: APP_NAME

            # Postgres
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: DATABASE_URL
              value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_DB_SERVICE_HOST):$(POSTGRES_DB_SERVICE_PORT)/$(POSTGRES_DB)

            - name: AWS_ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: AWS_ACCOUNT_ID
            - name: REGION
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: REGION
            - name: IMAGE_NAME
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: IMAGE_NAME
          ports:
            - containerPort: 8501
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
