kind: Service
apiVersion: v1
metadata:
  name: adrift
  namespace: adrift  # Sets Namespace
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: adrift
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
