apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    name: postgres-deployment
    app: postgres
    app.kubernetes.io/version: "15.2"
    app.kubernetes.io/component: database
  namespace: adrift  # Sets Namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15.2 # Sets Image
          imagePullPolicy: "IfNotPresent"
          ports:
          - containerPort: 5432  # Exposes container port
          env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
          - name: postgres-pv
            mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-pv
        persistentVolumeClaim:
          claimName: postgres-pvc        
      - name: postgres-pg-hba-config
        configMap:
          name: postgres-config-files
          items:
            - key: pg_hba.conf
              path: pg_hba.conf
