apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base/
- adrift-ingressroute.yaml
- adrift-application.yaml

#patchesStrategicMerge:
patches:
- path: application-patch.yaml
