# #01010ad9 -- # https://rgbacolorpicker.com/hex-to-rgba
# rgba(1, 1, 10, 0.85) -- # https://rgbacolorpicker.com/rgba-to-hex
[theme]
base="dark"
#primaryColor="purple"
#backgroundColor="#01010AD9"
#secondaryBackgroundColor="#F0F2F6"
#textColor="#262730"
font="sans serif"
