apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: adrift  # Sets Namespace
type: Opaque
data:
  # base64 encoded values only, local dev values
  POSTGRES_DB: YWRyaWZ0ZGIK
  POSTGRES_USER: YWRyaWZ0Cg==
  POSTGRES_PASSWORD: YWRyaWZ0Cg==
